version: '3.4'
services:
    perseo-core:
        image: fiware/perseo-core
        environment:
            - PERSEO_FE_URL=http://perseo-fe:9090
            - MAX_AGE=6000
        networks:
            - perseo
        depends_on:
            - mongo
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
    perseo-fe:
        image: fiware/perseo
        networks:
            perseo:
            main:
        ports:
            - 9090:9090
        depends_on:
            - perseo-core
        environment:
            - PERSEO_MONGO_ENDPOINT=localhost:27017
            - PERSEO_CORE_URL=http://perseo-core:8080
            - PERSEO_LOG_LEVEL=debug
            - PERSEO_ORION_URL=http://orion:1026/
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

networks:
    perseo:
    main:

volumes:
    mongodata:
        